name: 'ECS Service Update action'
description: 'Updates ECS Service'

inputs:
  cluster-name:
    description: 'Cluster to update'
    required: true
  family-name:
    description: 'Task family name'
    required: true
  aws-role:
    description: 'AWS Role to assume'
    required: true
  aws-region:
    description: 'AWS_REGION secret'
    required: true
  revision:
    description: 'Revision to install'
    required: true

runs:
  using: composite
  steps:
    - name: Print parameters
      run: echo Updating ecs service task ${{ inputs.family-name }} to revision ${{ inputs.revision }}
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: gh-actions-update-ecs-history-${{ inputs.family-name }}
        aws-region: ${{ inputs.aws-region }}
    - name: Update task definition
      run: |
        aws ecs update-service --cluster ${{ inputs.cluster-name }} \
          --service ${{ inputs.family-name }}-service \
          --task-definition ${{ inputs.family-name }}:${{ inputs.revision }} \
          --deployment-configuration maximumPercent=200,minimumHealthyPercent=100
          --region ${{ inputs.AWS_REGION }}}
      shell: bash