name: 'ECS task-def Update action'
description: 'Updates ECS task-def'

inputs:
  family-name:
    description: 'Task-def family name'
    required: true
  image-arn:
    description: 'Image ARN to use'
    required: true
  aws-role:
    description: 'AWS Role to assume'
    required: true
  aws-region:
    description: 'AWS_REGION secret'
    required: true
  ci-repo-url:
    description: 'CI_REPO_URL secret'
    required: true
  ci-repo-branch:
    description: 'Branch or tag of CI-repo'
    required: true
  ci-ssh-key:
    description: 'CI_SSH_KEY secret'
    required: true

runs:
  using: composite
  steps:
    - name: Print parameters
      run: echo Updating ecs task-def ${{ inputs.family-name }} to image ${{ inputs.image-arn }}
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.ci-repo-url }}
        ssh-key: ${{ inputs.ci-ssh-key }}
        ref: ${{ inputs.ci-repo-branch }}
        path: digitraffic-ci
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: gh-actions-update-ecs-history-${{ inputs.service-name }}
        aws-region: ${{ inputs.aws-region }}
    - name: Create new task-def
      run: jq -c '.containerDefinitions[0].image = "${{ inputs.image-arn }}"' digitraffic-ci/aws/task-def/${{ inputs.family-name }}-task-def.json > task-def.json
      shell: bash
    - name: Update task definition
      run: |
        aws ecs register-task-definition \
          --family ${{ inputs.family-name }} \
          --cli-input-json file://task-def.json \
          --region ${{ inputs.aws-region }} \
          > output.json
      shell: bash