name: 'Mirror action'
description: 'Mirror changes to another repository'
inputs:
  refspec:
    description: 'Refspec used in push'
    required: false
    default: 'master'
  mirror-repo:
    description: 'Mirroring to'
    required: true
  ssh-private-key:
    description: 'Private key'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - run: git push --follow-tags ${{ inputs.mirror-repo }} ${{ inputs.refspec }}
      shell: bash
