name: 'ECS Service Update action'
description: 'Updates ECS Service'

inputs:
  cluster-name:
    description: 'Cluster to update'
    required: true
  service-name:
    description: 'Task service name'
    required: true
  aws-role:
    description: 'AWS Role to assume'
    required: true
  aws-region:
    description: 'AWS_REGION secret'
    required: true
  task-definition:
    description: 'Task-def(and revision) to install'
    required: false
    default : ''
  desired-count:
    description: 'Desired count of service running'
    required: false
    default: '1'
  deployment-configuration:
    description: 'Configuration for deployment'
    required: false
    default: 'maximumPercent=200,minimumHealthyPercent=100'

runs:
  using: composite
  steps:
    - name: Print parameters
      run: echo Updating ecs service task ${{ inputs.service-name }} to ${{ inputs.task-definition }} with desired count ${{ inputs.desired-count }}
      shell: bash
    - name: Check parameters
      if: inputs.task-definition != '' && inputs.desired-count == '0'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('When desired-count is 0, you must not specify task-definition!')
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: gh-actions-update-ecs-${{ inputs.service-name }}
        aws-region: ${{ inputs.aws-region }}
    - name: Stop task
      if: inputs.desired-count == 0
      run: |
        aws ecs update-service --cluster ${{ inputs.cluster-name }} \
          --service ${{ inputs.service-name }} \
          --desired-count 0
        while [ $(aws ecs list-tasks --cluster ${{ inputs.cluster-name }} --service-name ${{ inputs.service-name }} | jq '.taskArns | length') -gt 0 ]; do echo 'Waiting'; sleep 1; done
      shell: bash
    - name: Update task definition
      if: inputs.desired-count != 0
      run: |
        aws ecs update-service --cluster ${{ inputs.cluster-name }} \
          --service ${{ inputs.service-name }} \
          --task-definition ${{ inputs.task-definition }} \
          --deployment-configuration ${{ inputs.deployment-configuration }} \
          --desired-count ${{ inputs.desired-count }}
      shell: bash
