name: 'Publish on GitHub Pages'
description: 'Publish a workflow artifact on GitHub Pages and link to it'
inputs:
  GH_PAGES_BRANCH:
    description: 'Branch for GitHub Pages content'
    required: false
    default: 'gh-pages'
  GH_PAGES_URL:
    description: 'GitHub Pages URL for current repo'
    required: true
  FILE_PATH:
    description: 'Path of file to be published, eg. target/report.html'
    required: true
  COMMIT_MESSAGE:
    description: 'Commit message when pushing to GitHub Pages branch'
    required: true
  LINK_TEXT:
    description: 'Text to display on link to file'
    required: true

runs: 
  using: 'composite'
  steps:
    - name: 'Publish file on GitHub Pages' 
      run: |
        git config --global user.email ""
        git config --global user.name "Github Actions"
        git add -f ${{ inputs.FILE_PATH }}
        git stash
        git fetch
        git switch ${{ inputs.GH_PAGES_BRANCH }}
        git rm --ignore-unmatch $(dirname ${{ inputs.FILE_PATH }})/*
        git checkout stash@{0} -- ${{ inputs.FILE_PATH }}
        git commit -am "${{ inputs.COMMIT_MESSAGE }}"
        git push -f
      shell: bash
    - name: 'Link to file in workflow summary'
      run: |
        export org=$(echo $GITHUB_REPOSITORY | sed -E 's/^([A-Za-z0-9_\-]+)\/.+$/\1/')
        export repo=$(echo $GITHUB_REPOSITORY | sed -E 's/^.+\/([A-Za-z0-9_\-]+)$/\1/')
        echo "[${{ inputs.LINK_TEXT }}](https://$org.github.io/$repo/${{ inputs.FILE_PATH }})" >> $GITHUB_STEP_SUMMARY
      shell: bash
