name: Build and deploy Hugo site to Pages
description: Builds and deploys a Hugo site to Github Pages with given configuration file

inputs:
  HUGO_VERSION:
    required: true
  CONFIG_FILE_PATH:
    required: false
    default: config.yml
  BRANCH:
    required: false
    default: ${{ github.event.repository.default_branch }}

runs:
  using: composite
  steps:
    - name: Install Hugo CLI
      shell: bash
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{inputs.HUGO_VERSION}}/hugo_extended_${{inputs.HUGO_VERSION}}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.BRANCH }}
        submodules: recursive
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Hugo
      env:
        # For maximum backward compatibility with Hugo modules
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      shell: bash
      run: |
        hugo \
          --baseURL "${{ steps.pages.outputs.base_url }}" \
          --minify \
          --config ${{ inputs.CONFIG_FILE_PATH }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
